### ISSUE TITLE
server_power_on/server_power_off/server_power_cycle_wait/server_power_cycle_immediate with rack_id throws error

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#11]
**ucsm_apis version**: Latest from Github
**Python version:** 2.7.12
**Operating System:** Windows 10

**Description -** 
Trying to power on/off the UCS managed rack server. It throws below error -

```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\server\test_power.py", line 37, in test_server_power_on_rack_server
    rack_id='1')
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\power.py", line 69, in server_power_on
    state=LsPowerConsts.STATE_UP)
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\power.py", line 50, in _service_profile_power_set
    if blade_mo.assigned_to_dn is None:
AttributeError: 'NoneType' object has no attribute 'assigned_to_dn'
```

Trying to power cycle the UCS managed rack server. It throws below error -

```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\server\test_power.py", line 72, in test_server_power_cycle_wait_rack_server
    rack_id='1')
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\power.py", line 113, in server_power_cycle_wait
    state="cycle-wait")
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\power.py", line 98, in _server_admin_power_set
    mo.admin_power = state
AttributeError: 'NoneType' object has no attribute 'admin_power'
```

**What I Did -**
Execute the following code -
```
server_power_on(handle=handle, rack_id='1')
server_power_off(handle=handle, rack_id='1')
server_power_cycle_wait(handle=handle, rack_id='1')
server_power_cycle_immediate(handle=handle, rack_id='1')
```

**Comment by ragupta-git** [comment]
Fixed in below PR.
https://github.com/CiscoUcs/ucsm_apis/pull/21

**Comment by tanmayx** [comment]
Verified. Marking as closed.
