### ISSUE TITLE
Error while getting boot policy

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#12]
**ucsm_apis version:** Latest code
**ucsmsdk version:** Latest code
**Python version:** 2.7.12
**Operating System:** Win 10

**Description**
Trying to get the boot policy which exists.

**What I Did**
_Executed the following code -_
```
boot_policy_get(handle=handle, name='boot_policy1')
```
_Observed the below error -_ 
```
ERROR: Nosetests.server.test_boot.test_boot_policy_create_default
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\server\test_boot.py", line 32, in test_boot_policy_create_default
    name='boot_policy1')
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\boot.py", line 46, in boot_policy_get
    dn = parent_dn + "/boot-policy-" + name
NameError: global name 'parent_dn' is not defined
```

**Comment by ragupta-git** [comment]
Fixed as part of PR - https://github.com/CiscoUcs/ucsm_apis/pull/14

**Comment by tanmayx** [comment]
Verified. Marking as closed.
