### ISSUE TITLE
Error while running boot_policy_exist

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#13]
**ucsm_apis version:** Latest code
**ucsmsdk version:** Latest code
**Python version:** 2.7.12
**Operating System:** Win 10

**Description**
Trying to check if boot policy exists.

**What I Did**
_Execute the following code -_
```
boot_policy_exist(handle=handle, name='boot_policy2')
```
_Observed below error -_
```
ERROR: Nosetests.server.test_boot.test_boot_policy_create
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\server\test_boot.py", line 46, in test_boot_policy_create
    descr='boot policy 2'))
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\boot.py", line 184, in boot_policy_exist
    mo = boot_policy_mo_get(handle=handle,
NameError: global name 'boot_policy_mo_get' is not defined
```

**Comment by tanmayx** [comment]
Verified. Marking as closed.
