### ISSUE TITLE
Error while modifying the boot policy

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#16]
**ucsm_apis version:** Latest code
**ucsmsdk version:** Latest code
**Python version:** 2.7.12
**Operating System:** Win 10

**Description**
Trying to modify the existing boot policy.

**What I Did**
_Execute the below code -_
```
boot_policy_modify(handle=handle, name='boot_policy1', reboot_on_update=True, enforce_vnic_name=False, boot_mode='uefi', descr='boot policy 1')
```
_Observed the below error -_
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\server\test_boot.py", line 58, in test_boot_policy_modify
    descr='boot policy 1')
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\boot.py", line 133, in boot_policy_modify
    mo.set_prop_multiple(**kwargs)
  File "c:\python27\lib\site-packages\ucsmsdk-0.9.3.1-py2.7.egg\ucsmsdk\ucsmo.py", line 129, in set_prop_multiple
    self.__set_prop(prop_name, kwargs[prop_name])
  File "c:\python27\lib\site-packages\ucsmsdk-0.9.3.1-py2.7.egg\ucsmsdk\ucsmo.py", line 224, in __set_prop
    value))
ValueError: Invalid Value Exception - [LsbootPolicy]: Prop <enforce_vnic_name>, Value<False>.
-------------------- >> begin captured logging << --------------------
ucs: DEBUG: enforce_vnic_name valid values are ['false', 'no', 'true', 'yes']
```

**Comment by tanmayx** [comment]
Verified. Marking as closed.
