### ISSUE TITLE
Error while setting the boot order for a policy where 'reboot_on_update' is not set

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#18]
**ucsm_apis version:** Latest code
**ucsmsdk version:** Latest code
**Python version:** 2.7.12
**Operating System:** Win 10

**Description**
Trying to set the boot order for a policy where ```reboot_on_update=False```

**What I Did**
_Execute the following code -_
```
boot_devices = [
        {
            'device_name':'local_disk',
            'device_order':'1'
        }
    ]
    obj = boot_policy_get(handle=handle, name='boot_policy2')
    boot_policy_order_set(handle=handle, boot_policy_dn=obj.dn, devices=boot_devices)
```
_Observed below error -_
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\server\test_boot.py", line 84, in test_boot_policy_order_set
    devices=boot_devices)
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\boot.py", line 715, in boot_policy_order_set
    _boot_policy_order_clear(handle, boot_policy)
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\server\boot.py", line 694, in _boot_policy_order_clear
    boot_policy.reboot_on_update = False
  File "c:\python27\lib\site-packages\ucsmsdk-0.9.3.1-py2.7.egg\ucsmsdk\ucsmo.py", line 173, in __setattr__
    self.__set_prop(name, value)
  File "c:\python27\lib\site-packages\ucsmsdk-0.9.3.1-py2.7.egg\ucsmsdk\ucsmo.py", line 224, in __set_prop
    value))
ValueError: Invalid Value Exception - [LsbootPolicy]: Prop <reboot_on_update>, Value<False>.
-------------------- >> begin captured logging << --------------------
ucs: DEBUG: reboot_on_update valid values are ['false', 'no', 'true', 'yes']
```

**Comment by tanmayx** [comment]
Verified. Marking as closed.
