### ISSUE TITLE
Executing callhome_system_inventory_send_now() throws NameError

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#30]
ucsm_apis version: Latest code
Python version: 2.7.12
Operating System: Win 10

**Description**
_Trying to execute callhome_system_inventory_send_now() API_

**What I Did**
_Execute the below code -_
```
callhome_system_inventory_send_now(handle=handle)
```

_Observed below error -_
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\admin\test_callhome.py", line 744, in test_callhome_system_inventory_send_now
    obj = callhome_system_inventory_send_now(handle=handle)
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\admin\callhome.py", line 738, in callhome_system_inventory_send_now
    mo.set_prop_multiple(**kwargs)
NameError: global name 'kwargs' is not defined
```

**Comment by ragupta-git** [comment]
Fixed in PR: Added exists api and few fixes for callhome apis #48
