### ISSUE TITLE
trusted_point_modify() API throws UcsException when try to modify policy_owner and cert_chain params

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#31]
ucsm_apis version: Latest code
Python version: 2.7.12
Operating System: Win 10

**Description**
When try to modify the trusted point with `policy_owner` and `cert_chain` params, the api throws UcsException.

**What I Did**
Execute the below code
```
trusted_point_modify(handle=handle, name='tp-03', policy_owner='pending-policy', cert_chain='abc')
```

Observed below exception -
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\admin\test_keyring.py", line 200, in test_trusted_point_modify
    policy_owner='local')
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\admin\keyring.py", line 427, in trusted_point_modify
    handle.commit()
  File "c:\python27\lib\site-packages\ucsmsdk-0.9.3.1-py2.7.egg\ucsmsdk\ucshandle.py", line 916, in commit
    raise UcsException(response.error_code, response.error_descr)
UcsException: [ErrorCode]: 170[ErrorDescription]: Policies of type pkiTP are managed from remote policy server. Create/Delete/Modify operations are not allowed.
```

But when try to modify the `descr` param, it works fine

**Comment by tanmayx** [comment]
Able to modify the `cert_chain` value now. Verified. Marking as closed.
