### ISSUE TITLE
ldap_provider_group_provider_get() throws Exception

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#32]
ucsm_apis version: Latest code
Python version: 2.7.12
Operating System: Win 10

**Description**
Trying to execute ldap_provider_group_provider_get() API.

**What I Did**
```
obj = ldap_provider_group_provider_get(handle=handle, group_name='abcd', name='10.65.183.72')
print obj
```

**Observed the below error -**
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\admin\test_ldap.py", line 210, in test_ldap_provider_group_provider_add
    name='10.65.183.72')
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\admin\ldap.py", line 818, in ldap_provider_group_provider_get
    "Ldap Provider Reference '%s' does not exist" % provider_ref_dn)
UcsOperationError: ldap_provider_group_provider_get failed, error: Ldap Provider Reference 'sys/ldap-extprovidergroup-abcd/provider-ref-10.65.183.72' does not exist
```

**Comment by ragupta-git** [comment]
Fixed in PR: Added and modified exists api for ldap related config. #42

**Comment by tanmayx** [comment]
Verified. Marking as closed.
