### ISSUE TITLE
password_strength_uncheck() API throws error

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#36]
* ucsm_apis version: Latest code
* Python version: 2.7.12
* Operating System: Win 10

**Description -**
Trying to un-check the password strength checkbox using `password_strength_uncheck()` API. It throws error.

**What I Did -**
Execute below code
```
password_strength_uncheck(handle=handle)
```

Observed below error -
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\admin\test_user.py", line 202, in test_password_strength_uncheck
    obj = password_strength_uncheck(handle=handle)
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\admin\user.py", line 543, in password_strength_uncheck
    mo.set_prop_multiple(**kwargs)
NameError: global name 'kwargs' is not defined
```

**Comment by ragupta-git** [comment]
Fixed in PR: Added exists api for password strength and profile. #41

**Comment by tanmayx** [comment]
Verified. Marking as closed.
