### ISSUE TITLE
tacacsplus_provider_group_provider_get() throws NameError

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#37]
ucsm_apis version: Latest code
Python version: 2.7.12
Operating System: Win 10

**Description -**
Try to get the details of tacacsplus provider from the provider group. It throws the NameError.

 **What I Did -**
Executed the below code
```
obj = tacacsplus_provider_group_provider_get(handle=handle, group_name='tacacsgroup1', name='tacacs1')
```

Observed below error -
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_Ucsm\Nosetests\admin\test_tacacsplus.py", line 92, in test_tacacsplus_provider_group_provider_add
    name='tacacs1')
  File "c:\python27\lib\site-packages\ucsm_apis-0.9.0.0-py2.7.egg\ucsm_apis\admin\tacacsplus.py", line 357, in tacacsplus_provider_group_provider_get
    mo = handle.query_dn(provider_dn)
NameError: global name 'provider_dn' is not defined
```

**Comment by ragupta-git** [comment]
Fixed in PR: modified exists apis for tacacsplus config #45

**Comment by tanmayx** [comment]
Verified. Marking it closed.
